import = [
    # "~/.config/alacritty/themes/themes/everforest_dark.toml"
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]

live_config_reload = true 

[shell]
program = "/bin/zsh"
args = ["-l"]

[env]
TERM = "xterm-256color"

[font]
size = 11.0
normal = { family = "JetBrainsMonoNL Nerd Font", style="Normal"}
#[font.normal]
#family = "JetBrainsMono NFM"

[window]
startup_mode = "Windowed"
dynamic_padding = true
opacity = 1
blur = true
decorations = "Full"
title = "~~je suis terminal~~"
dynamic_title = false 

[window.padding]
x = 0
y = 0

[window.dimensions]
columns=120
lines=50

[cursor]
style = {shape = "Block", blinking = "On"}
